import re
import json

text = '''
COCO COINS PRICE 150 RS
TWIX IMP PRICE 100 RS
MARS IMP PRICE 100 RS
KINDER BUENO PRICE 120 RS
M&M CHOCOLATE PRICE 100 RS
ALPENLIEBE PRICE 100 RS
RICOLA PRICE 200 RS
DR MINTS PRICE 450 RS
MENTOS GRAPE PRICE 50 RS
MENTOS BERRYGOOD PRICE 100 RS
MENTOS MINT PRICE 50 RS
MENTOS BUAH PRICE 50 RS
MENTOS RAINBOW PRICE 50 RS
FRUIT-TELLA ORANGE PRICE 100 RS
TOMMY FRUITY PRICE 40 RS
FRUIT-TELLA B.CURRENT PRICE 100 RS
FRUIT-TELLA STRAWBERRY PRICE 100 RS
BATOOK ORANGE PRICE 20 RS
BATOOK BANANA PRICE 20 RS
BATOOK CARDAMOM PRICE 20 RS
TRIDENT GUM PRICE 120 RS
COOLMINT PRICE 20 RS
ICE BREAKERS DIA PRICE 30 RS
ICE BREAKERS ROUND PRICE 250 RS
LIPS STRAWBERRY PRICE 50 RS
HUBBA BUBBA PRICE 200 RS
SOUR PUNK PRICE 40 RS
ICE BREAKERS COOL PRICE 50 RS
MENTOS PURE PRICE 150 RS
AMIRA CANDY PRICE 150 RS
COCON PACK OF 3 PRICE 100 RS
ZAZZY MINI PRICE 20 RS
NESCAFE LATTE PRICE 400 RS
NESCAFE CAPPUCCINO PRICE 400 RS
NESCAFE CARAMEL LATTE PRICE 400 RS
MELODY POPS PRICE 75 RS
NESCAFE VANILLA LATTE PRICE 400 RS
NESCAFE IRISH LATTE PRICE 400 RS
ZAZIO DATE SYRUP PRICE 399 RS
ZAZIO DATTY NUTTY PRICE 649 RS
CADBURY HOT CHOCO PRICE 500 RS
MILO IMP PRICE 550 RS
GALAXY MOCHA PRICE 900 RS
GALAXY CAREMAL PRICE 900 RS
GALAXY CHOCOLATE PRICE 900 RS
NESCAFE 3 IN 1 PRICE 700 RS
MAGIC POPS PRICE 10 RS
CHIKEN STOCK PRICE 810 RS
VEG STOCK PRICE 700 RS
WEETABIX PRICE 430 RS
REGGIA LASAGNE PRICE 350 RS
TESCO YEAST PRICE 400 RS
TACO SEASON PRICE 200 RS
STARBUST DRINK PRICE 320 RS
QUAKE OATS PRICE 349 RS
JOLLY RANCHER DRINK PRICE 320 RS
WELCH DRINK PRICE 320 RS
NUTELLA MINI PRICE 99 RS
MARETTI BRUSCHETTA PRICE 100 RS
TAJIN PRICE 80 RS
YOKOSO NOODLES PRICE 200 RS
SPLENDA SWEETNER PRICE 400 RS
TABASCO JALAPENO PRICE 310 RS
TABASCO PEPPER 250 RS
TABASCO GARLIC 490 RS
ZAZIO HOTSAUCE PRICE 79 RS
FILIPPO PESTO PRICE 79 RS
NESTLE SMARTIES PRICE 130 RS
HELLMANNS PRICE 450 RS
BULDAK PRICE 440 RS EACH
ALMARAI PRICE 450 RS EACH
PUCK STICKS PRICE 550 RS
FRESHO CREAM PRICE 275 RS EACH
KRAFT CHEDDAR PRICE 400 RS
FRESHOS DIJON MUSTARD PRICE 299 RS
US MUSTARD PRICE 240 RS
KARA CREAM PRICE 210 RS
KARA COCONUT MILK PRICE 190 RS
FUSEN GUM PRICE 25 RS
NUTELLA BIG PRICE 399 RS
MOMENTS CREAM PRICE 600 RS
HERSHEYS SYRUP PRICE 300 RS
NERDS SMALL PRICE 200 RS
NERDS BIG PRICE 350 RS
HAPPY HIPPO PRICE 400 RS
RAFFAELLO WHITE PRICE 110 RS
FERRERO ROCHER PRICE 169 RS
MILKA LEO PRICE 125 RS
MR BEAST FEASTABLES PRICE 499 RS
IMPACT MINTS PRICE 150 RS
TOBLERONE DARK PRICE 320 RS
TOBLERONE NORMAL PRICE 320 RS
TOBLERONE FRUIT & NUT PRICE 300 RS
TOBLERONE CRUNCHY PRICE 350 RS
KITKAT BIG HAZELNUT PRICE 400 RS
GANDOUR SAFARI RICH PRICE 10 RS
BOUNTY PRICE 100 RS
KITKAT COCOA PRICE 150 RS
KITKAT WHITE PRICE 150 RS
SNICKERS NORMAL PRICE 20 RS
SNICKERS IMP PRICE 100 RS
KITKAT NORMAL PRICE 70 RS
MARS BIG PRICE 780 RS
'''

lines = [line.strip() for line in text.strip().split('\n')]
products = []
for i, line in enumerate(lines):
    match = re.search(r'(.*?)(?:PRICE\s+)?(\d+)\s*(?:RS|EACH|RS EACH)?$', line, re.IGNORECASE)
    if match:
        name = match.group(1).strip()
        name = re.sub(r'(?i)\s*PRICE$', '', name)
        price = int(match.group(2))
        
        name_lower = name.lower()
        if any(x in name_lower for x in ['choco', 'mars', 'twix', 'kinder', 'snickers', 'bounty', 'toblerone', 'm&m', 'galaxy', 'ferrero', 'milka', 'kitkat', 'hershey', 'nutella', 'gandour', 'raffaello', 'mr beast']):
            cat = 'Chocolates'
        elif any(x in name_lower for x in ['mentos', 'candy', 'pops', 'gum', 'trident', 'hubba', 'mints', 'nerds', 'fruit-tella', 'alpenliebe', 'ricola', 'batook', 'ice breakers']):
            cat = 'Candy'
        elif any(x in name_lower for x in ['drink', 'nescafe', 'milo', 'syrup']):
            cat = 'Drinks'
        elif any(x in name_lower for x in ['bruschetta', 'lasagne', 'noodles', 'oats', 'weetabix', 'cake', 'cookie', 'biscuit']):
            cat = 'Biscuits'
        else:
            cat = 'Other'
            
        products.append({
            'id': f'r1_{i+1}',
            'name': name,
            'price': price,
            'image': f'/products/{name.lower().replace(" ", "_").replace("-", "_").replace("&", "and")}.png',
            'category': cat,
            'country': ''
        })

with open('src/components/parsed_products.json', 'w') as f:
    json.dump(products, f, indent=2)
print(f'Wrote {len(products)} products')
